[package]
name = "fiboa-rs-spawn"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
wit-bindgen.workspace = true
wasip2.workspace = true
wstd.workspace = true
