wasm.backtrace.persist = false
activities.directories.enabled = true

[log.console]
enabled = true

[[activity_wasm]]
name = "fiboa_rs_spawn"
location = "oci://docker.io/getobelisk/benchmark_fibo_fiboa_rs_spawn:2026-02-12@sha256:e272d3011cd47e9aaec8abf799e527d4980a5190df3a6cfb270ffd64557df7da"
max_retries = 0
exec.lock_expiry.seconds = 25
env_vars = ["FIBO_EXE_PATH"]
directories  = { enabled = true, reuse_on_retry = false, process_provider = "native"}

[[workflow]]
name = "fibow_rs"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_rs:2026-02-12@sha256:6a4c10869620d88c0ace89d4639d9e8e7ad8c1f0fc6877af26ee4883d86f92cf"
exec.lock_expiry.seconds = 2
