api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_js"
location.path = "${OBELISK_TOML_DIR}/activity/js/dist/fiboa-js.wasm"
max_retries = 0
exec.lock_expiry.seconds = 5

[[workflow]]
name = "fibow_js"
location.path = "${OBELISK_TOML_DIR}/workflow/js/dist/fibow-js.wasm"
exec.lock_expiry.seconds = 2
