[[activity_wasm]]
name = "fiboa_go"
location = "oci://docker.io/getobelisk/benchmark_fibo_fiboa_go:2026-07-13@sha256:1020bbe397b152976031a843143a4e2f9b1b2138878ffea744da614a904360dd"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow_wasm]]
name = "fibow_go"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_go:2026-07-13@sha256:3ab6e491d0e53cc37a429fd8a42079654fe2c188d586a7eb0c93c04e7bda97c3"
exec.lock_expiry.seconds = 2
stub_wasi = true # TinyGo limitation
