[[activity_wasm]]
name = "fiboa_go"
location = "oci://docker.io/getobelisk/benchmark_fibo_fiboa_go:2026-06-24@sha256:dd001775edf1f8a391201ba301fc05d7ab01ea7b38ee167d1a9bfcae92ba30ae"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow_wasm]]
name = "fibow_go"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_go:2026-06-24@sha256:f842e0d03247acc94588613afda666e8cd5d07fdef93bd4917ec58e2b47b35cd"
exec.lock_expiry.seconds = 2
stub_wasi = true # TinyGo limitation
