[[activity_js]]
name = "fiboa_js_native"
location = "oci://docker.io/getobelisk/benchmark_fibo_fiboa_js_native:2026-07-13@sha256:854c2b8210d67548ee50dace825a1954f5a6fef74b28b001535002e50ee6a9e7"
ffqn = "benchmark-fibo:activity/fiboa.fibo"
return_type = "result<u64, string>"
exec = { lock_expiry = { seconds = 25 } }

[[activity_js.params]]
name = "n"
type = "u8"

[[workflow_js]]
name = "fibow_js_native"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_js_native:2026-07-13@sha256:6af61462f64e7698780c909ea196ef0af6a841fb34b4cbb9cd1df09b7627d3b3"
ffqn = "benchmark-fibo:workflow/fibow.fiboa"
return_type = "result<u64, string>"
exec = { lock_expiry = { seconds = 2 } }

[[workflow_js.params]]
name = "n"
type = "u8"

[[workflow_js.params]]
name = "iterations"
type = "u32"

[[workflow_js]]
name = "fibow_concurrent_js_native"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_concurrent_js_native:2026-07-13@sha256:d99516ecae1e8c383302fe72b1bb207934acb3b7cb7b94895f34131b114f741f"
ffqn = "benchmark-fibo:workflow/fibow.fiboa-concurrent"
return_type = "result<u64, string>"
exec = { lock_expiry = { seconds = 2 } }

[[workflow_js.params]]
name = "n"
type = "u8"

[[workflow_js.params]]
name = "iterations"
type = "u32"
