wasm.backtrace.persist = false

[log.console]
enabled = true

[[activity_wasm]]
name = "fiboa_rs"
location = "${OBELISK_TOML_DIR}/target/wasm32-wasip2/release_activity/fiboa_rs.wasm"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_rs"
location = "${OBELISK_TOML_DIR}/target/wasm32-unknown-unknown/release_workflow/fibow_rs.wasm"
exec.lock_expiry.seconds = 2
