wasm.backtrace.persist = false

[log.console]
enabled = true

[[activity_wasm]]
name = "fiboa_go"
location = "${OBELISK_TOML_DIR}/activity/go/dist/fiboa-go.wasm"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_go"
location = "${OBELISK_TOML_DIR}/workflow/go/dist/fibow-go.wasm"
exec.lock_expiry.seconds = 2
stub_wasi = true # TinyGo limitation
