wasm.backtrace.persist = false

[log.console]
enabled = true

[[activity_wasm]]
name = "fiboa_js"
location = "${OBELISK_TOML_DIR}/activity/js/dist/fiboa-js.wasm"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_js"
location = "${OBELISK_TOML_DIR}/workflow/js/dist/fibow-js.wasm"
exec.lock_expiry.seconds = 2
