api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

wasm.backtrace.persist = false

[log.stdout]
enabled = true

[[activity_wasm]]
name = "fiboa_py"
location.path = "${OBELISK_TOML_DIR}/activity/py/dist/fiboa-py.wasm"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow]]
name = "fibow_py"
location.path = "${OBELISK_TOML_DIR}/workflow/py/dist/fibow-py.wasm"
exec.lock_expiry.seconds = 2
