[[activity_exec]]
name = "fiboa_rs_spawn"
location = "oci://docker.io/getobelisk/benchmark_fibo_fiboa_rs_spawn:2026-07-13@sha256:f656bce908ff8b57a220fc1812095ddfd447c4be2562a1d7f2597a1179e21147"
ffqn = "benchmark-fibo:activity/fiboa.fibo"
return_type = "result<u64>"
env_vars = ["FIBO_EXE_PATH"]
exec = { lock_expiry = { seconds = 25 } }
max_output_bytes = 4096

[[activity_exec.params]]
name = "n"
type = "u8"

[[workflow_wasm]]
name = "fibow_rs"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_rs:2026-07-13@sha256:db88f7a7e04927ce4e527237509e62563a2623dd432bc9c2db1a7b12031a6713"
exec.lock_expiry.seconds = 2
