[[activity_wasm]]
name = "fiboa_js"
location = "oci://docker.io/getobelisk/benchmark_fibo_fiboa_js:2026-04-08@sha256:519a2ea580ee0bb22e75330e3ae0bb512b99e08ba2c702dcf79894515196bfd1"
max_retries = 0
exec.lock_expiry.seconds = 25

[[workflow_wasm]]
name = "fibow_js"
location = "oci://docker.io/getobelisk/benchmark_fibo_fibow_js:2026-04-08@sha256:aba90b93b830abfaed7ae2d7de0ac469cedcd908b0109bbc5059dfbb29949186"
exec.lock_expiry.seconds = 2
